-- 코드를 입력하세요
SELECT FIRST_HALF.FLAVOR
from FIRST_HALF, ICECREAM_INFO
where FIRST_HALF.flavor = ICECREAM_INFO.flavor AND FIRST_HALF.TOTAL_ORDER >= 3000 AND ICECREAM_INFO.INGREDIENT_TYPE = 'fruit_based'