-- 코드를 입력하세요
select I.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS, ROUND(AVG(R.REVIEW_SCORE), 2) AS SCORE
from REST_INFO AS I, REST_REVIEW AS R
where I.ADDRESS like '서울%' AND I.REST_ID = R.REST_ID
group by I.REST_ID
order by SCORE desc, FAVORITES desc